# Generated by Django 5.2.6 on 2025-10-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField()),
                ('purchase_year_month', models.CharField()),
                ('cost', models.IntegerField()),
                ('accu_depre', models.IntegerField()),
                ('net_book_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField()),
                ('revenue', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('profit_loss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month_date', models.CharField()),
                ('manager_name', models.CharField()),
                ('phone_number', models.CharField()),
            ],
        ),
    ]
