# Generated by Django 5.2.6 on 2025-10-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='year_month',
            new_name='description',
        ),
    ]
