# Generated by Django 5.2.6 on 2025-10-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_year_month_asset_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='accu_depre',
            new_name='accu_depre_million',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='cost',
            new_name='cost_million',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='net_book_value',
            new_name='net_book_value_million',
        ),
    ]
