# Generated by Django 5.2.6 on 2025-10-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_accu_depre_asset_accu_depre_million_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financial',
            old_name='expenses',
            new_name='expenditure_thousand',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='profit_loss',
            new_name='profit_loss_thousand',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='revenue',
            new_name='revenue_thousand',
        ),
    ]
