# Generated by Django 5.2.6 on 2025-10-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_rename_expenses_financial_expenditure_thousand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='year_month_date',
            new_name='year_month_day',
        ),
    ]
